"""changed text to not nullable

Revision ID: 44de6add6dc2
Revises: aa55dd9ae573
Create Date: 2025-01-22 21:45:00.432337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44de6add6dc2'
down_revision: Union[str, None] = 'aa55dd9ae573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
